[phases.setup]
nixPkgs = ["python310", "playwright-driver", "chromium"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["playwright install chromium"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
